baseURL = "https://mutti.fi/"
languageCode = "fi"
title = "Muttisivu"
theme = "ananke"
pluralizelisttitles = false
summaryLength = 15
show_reading_time = true


logo = "images/mutti_logo.jpg"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "avenir bg-near-white"
  favicon = "images/mutti_logo.jpg"
  description = "Viimeinen luotto-sivu, jota tarvitset. Ehkä."
  facebook = "#"
  twitter = "#"
  instagram = "#"
  youtube = "#"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = "/images/7.jpg"
  recent_posts_number = 2

  pageNotFoundTitle = "404 - Sivua ei löytynyt"
